#----------------GitHub Actions------------

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask_deploy_version_${{ github.sha }}"

on: 
  push: 
    branches: 
      - main

jobs:
  my-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello World from testing job"
      - name: Execute few commands
        run: |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "APPLICATION_NAME: ${{ env.APPLICATION_NAME }}"
    

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
      - name: Print Hello Message in Deploy
        run: echo "Hello World from Deploy job"

      - name: Deployment package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        
        
        
        
    
