#----------------GitHub Actions------------__

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask_deploy_version_${{ github.sha }}"

on: 
  push: 
    branches: 
      - main

jobs:
  my-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello World from testing job"

      - name: Execute few commands
        run: |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "APPLICATION_NAME: ${{ env.APPLICATION_NAME }}"
          

      - name: Print current folder
        run: ls -la
        
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: Print current folder
        run: ls -la

    

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    env: 
      VAR1: "This is variable for Deploy AAAAAAAAAAAAAAAA"
    
    steps:
      - name: Print Hello Message in Deploy
        run: echo "Hello World from Deploy job"
      - name: Print any vars
        run: |
          echo "VAr1 : ${{ env.VAR1 }}"
          echo "LOCAL VAR : $LOCAL_VAR"
        env:
          LOCAL_VAR: "SUPER LOCAL VARIABLE1"

      - name: Deployment package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        
      - name: Lest test some packeges if they are here 1
        run: aws --version
        
      - name: Lest test some packeges if they are here 2
        run: zip
        
        
    
